channels:
     1: DPC
     2: Alexa488
     3: Cy5

metadata:
    Row: Row
    Col: Col
    FieldID: FieldID
    PlaneID: PlaneID
    TimepointID: TimepointID
    SequenceID: SequenceID
    PositionX: PositionX
    PositionY: PositionY
    PositionZ: PositionZ
    AbsPositionZ: AbsPositionZ
    AbsTime: AbsTime
#    ImageResolutionX: ImageResolutionX
#    ImageResolutionY: ImageResolutionY
#    ImageSizeX: ImageSizeX
#    ImageSizeY: ImageSizeY
#    BinningX: BinningX
#    BinningY: BinningY
#    MaxIntensity: MaxIntensity
#    ObjectiveMagnification: ObjectiveMagnification
#    ObjectiveNA: ObjectiveNA
#    ExposureTime: ExposureTime
